
##
GET http://localhost:8080/api/v1/mobile/eleves
###

###

GET http://localhost:8080/api/v1/classes/professeur/68366198d5748c5c10e824cb

###
GET http://localhost:8080/api/v1/mobile/pointage/byVigileId/683bad275fe4a742e54c7f8d

###

POST http://localhost:8080/api/v1/mobile/pointage/valider-presence
Accept: application/json
Content-Type: application/json

{
        "eleveId": "683dafd5827bef35f1e72a19",
        "heureArrivee": "2025-06-02T15:00:00.000Z",
        "idVigile": "683dafc9827bef35f1e729ef"
}

###

GET http://localhost:8080/api/v1/justificatif

###

GET http://localhost:8080/api/v1/professeurs


###

GET http://localhost:8080/api/v1/mobile/pointage/elevesjour

###

GET http://localhost:8080/api/v1/mobile/eleves/683b34d621cd3269b4056b4b

###

GET http://localhost:8080/api/v1/mobile/classes

###

GET http://localhost:8080/api/v1/cours/eleve/683d74bd827bef35f1e72617/today

###
GET http://localhost:8080/api/v1/mobile/justifier/eleve/6836e7b75bf44a56b8f5f78e

###

GET http://localhost:8080/api/v1/mobile/cours/Date/2025-05-30T07:00:00.000+00:00
###

GET http://localhost:8080/api/v1/mobile/cours
###

GET http://localhost:8080/api/v1/mobile/classes/6836e7ae5bf44a56b8f5f75c

###
GET http://localhost:8080/api/v1/mobile/cours/eleve/6836e7b75bf44a56b8f5f78e

###

GET http://localhost:8080/api/v1/classes/professeur/6836285320fe0370c39e7f3c

###

GET http://localhost:8080/api/v1/cours/classe/6836bead5479bc17875f516c?startDate=2025-03-26&endDate=2025-03-30 
###

POST http://localhost:8080/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "login": "eleve0",
    "password": "eleve0"
}


###
GET http://localhost:8080/api/v1/professeurs/6835e02348427748f7081935

###


GET http://localhost:8080/api/v1/eleves/1

###

GET http://localhost:8080/api/v1/niveau

###

GET  http://localhost:8080/api/v1/classes/professeur/6836285320fe0370c39e7f3c

###

GET http://localhost:8080/api/v1/cours/classe/6836bead5479bc17875f516c?startDate=2025-05-27&endDate=2025-06-02 

###

GET http://localhost:8080/api/v1/cours/professeur/1?startDate=2025-03-26&endDate=2025-03-30 


###


POST http://localhost:8080/api/v1/mobile/justifier
Accept: application/json
Content-Type: application/json

{
        "justificatif": "je suis dead",
        "statutJustification": "EN_ATTENTE",
        "abscenceId": "6836e80b5bf44a56b8f5f86d",
        "imageUrl": "https://i.pinimg.com/564x/00/9c/0b/009c0b8e2b4f9b4b4b4b4b4b4b4b4b4b.jpg"       
}


###

GET http://localhost:8080/api/v1/mobile/abscences/eleve/683d74bd827bef35f1e7261a


###

PUT http://localhost:8080/api/v1/mobile/abscences/update/683997f114d219133e657141
Accept: application/json
Content-Type: application/json

{
        "statutAbscence": "JUSTIFIER",
        "eleveId": "683997d214d219133e657125",
        "justificatifId": "6836e80b5bf44a56b8f5f86d",
        "coursId": "683997d814d219133e657138",
        "typeAbscence": "Absent"
        

}


###

POST http://localhost:8080/api/v1/mobile/abscences

     
###
Get http://localhost:8080/api/v1/abscences

###

Get http://localhost:8080/api/v1/abscences/update/683b653fcb355527cb77dac2

###
PUT http://localhost:8080/api/v1/justificatif/abscence/683b6549cb355527cb77dac5
Accept: application/json
Content-Type: application/json

{
        "statutJustificatif": "VALIDE"
}
###

GET http://localhost:8080/api/v1/mobile/eleves/user/683d74bb827bef35f1e72612

###



GET http://localhost:8080/api/v1/mobile/vigiles/user/683d74ac827bef35f1e725eb
